apiVersion: v1
kind: Service
metadata:
  name: seichiassist-distributor-service
  namespace: seichi-minecraft
  labels:
    app: seichiassist-distributor
spec:
  selector:
    eventsource-name: seichiassist-distributor
  ports:
    - protocol: TCP
      port: 12000
      targetPort: 12000
      name: http
  type: ClusterIP
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: seichiassist-distributor
  namespace: seichi-minecraft
spec:
  eventBusName: seichiassist-distributor
  github:
    SeichiAssistReleaseEventSource:
      repositories:
        - owner: GiganticMinecraft
          names:
            - SeichiAssist
      webhook:
        endpoint: /create-seichiassist-release
        port: "12000"
        method: POST
        url: https://argo-wf-webhook.onp-k8s.admin.seichi.click
      events:
        - "release"
      apiToken:
        name: argo-events-github-access-token
        key: ARGO_EVENTS_GITHUB_ACCESS_TOKEN
