# 外部から Argo Workflows を発火するためには Cloudflared を使えば機能的には問題がないが、
# 任意のクライアントから GET を受け付けると面倒なので、POST だけに限定するためのリバースプロキシを挟む。
apiVersion: v1
kind: Service
metadata:
  name: seichiassist-dist-proxy
  namespace: seichi-minecraft
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: seichiassist-dist-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seichiassist-dist-proxy
  namespace: seichi-minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seichiassist-dist-proxy
  template:
    metadata:
      labels:
        app: seichiassist-dist-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.1
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d/proxy.conf
              subPath: proxy.conf
      volumes:
        - name: conf
          configMap:
            name: seichiassist-dist-proxy-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seichiassist-dist-proxy-cm
  namespace: seichi-minecraft
data:
  proxy.conf: |
    server_names_hash_bucket_size 128;

    server {
      listen 80;
      server_name seichiassist-dist.onp-k8s.admin.seichi.click;
      location / {
        limit_except POST {
          deny all;
        }
        proxy_pass http://seichiassist-distributor-service:12000;
        proxy_request_buffering off;
      }
    }
