apiVersion: v1
kind: Service
metadata:
  name: mcserver--debug-s16
  labels:
    app: mcserver
    role: metrics
    mcserver: debug-s16
spec:
  type: ClusterIP
  ports:
    - name: minecraft
      port: 25565
      protocol: TCP
      targetPort: minecraft
    - name: jmx-metrics
      port: 18321
      protocol: TCP
      targetPort: jmx-metrics
  selector:
    mcserver: debug-s16
